import worldFlags from "../../data/flags.json"
import countryStatsData from "../../data/countryStats.json"
import countryCentroidsData from "../../data/countryCentroids.json"

/**
 * The shared country pool - every country we know enough about to build a
 * puzzle from: a flag, a capital and a complete stats row. Daily Connections
 * and Daily Deduction both draw from here, so a country either exists for both
 * modes or for neither.
 */

export type CountryEntry = {
    code: string
    /** Primary name, the one shown in the UI. */
    name: string
    /** Every accepted spelling, for matching what a player typed. */
    names: string[]
    image: string
    capital: string
    region: string
    subregion: string
    area: number
    population: number
    currency: string
    difficulty: number
}

type FlagRow = {
    code: string
    name: string | string[]
    capital?: (string | null)[] | null
    image: string
    difficulty?: number
}

type StatRow = {
    common: string
    official: string
    capital: string
    region: string
    subregion: string
    area: number
    population: number
    currency: string
}

/** Never used as a puzzle answer: dependencies, constituent countries, Antarctica. */
const EXCLUDED_CODES = new Set([
    "aq", "gb-eng", "gb-sct", "gb-wls", "gb-nir", "hk", "mo", "pr", "gl", "fo",
])

const STATS = countryStatsData as unknown as Record<string, StatRow>

export const POOL: CountryEntry[] = (worldFlags as unknown as FlagRow[]).flatMap(row => {
    if (EXCLUDED_CODES.has(row.code)) return []
    const stat = STATS[row.code]
    if (!stat) return []
    const capital = (row.capital && row.capital[0]) || stat.capital || ""
    if (!capital) return []
    const names = Array.isArray(row.name) ? row.name : [row.name]
    return [{
        code: row.code,
        name: names[0],
        names,
        image: row.image,
        capital,
        region: stat.region || "",
        subregion: stat.subregion || "",
        area: stat.area || 0,
        population: stat.population || 0,
        currency: stat.currency || "",
        difficulty: typeof row.difficulty === "number" ? row.difficulty : 3,
    }]
})

const BY_CODE = new Map(POOL.map(c => [c.code, c]))

export function countryByCode(code: string): CountryEntry | undefined {
    return BY_CODE.get(code)
}

/**
 * `[longitude, latitude]` per country, generated by `scripts/gen-centroids.mjs`
 * from the world map. It is the centre of a country's largest landmass, so a
 * bearing between two of them reads the way a player expects.
 */
export const CENTROIDS = countryCentroidsData as unknown as Record<string, [number, number]>

export function centroidOf(code: string): [number, number] | undefined {
    return CENTROIDS[code]
}
